### ISSUE TITLE
bottom up saliency

### ISSUE THREAD

**Issue by nationalflag** [rohitgirdhar/AttentionalPoolingAction#10]
So, the algorithm seems to replace the average pooling with a weighted pooling using bottom up saliency as the weight?

**Comment by nationalflag** [comment]
The bottom up saliency maps showed in Fig 2  are pose regularized or not?

**Comment by rohitgirdhar** [comment]
Reg the algorithm: yes that's correct
Reg saliency maps in Fig 2: They are not pose-regularized.
