### ISSUE TITLE
Error message  --  undefined symbol: _ZN2cv8fastFreeEPv

### ISSUE THREAD

**Issue by zhihuilics** [rohitgirdhar/AttentionalPoolingAction#13]
Hi,

I am trying to run the evaluation script. However, I got the following error message.

undefined symbol: _ZN2cv8fastFreeEPv

Could you please let me know how to solve this issue?

Thanks.

**Comment by rohitgirdhar** [comment]
Did you try #2?

**Comment by rohitgirdhar** [comment]
Closing because of no response.
