### ISSUE TITLE
Error: /usr/bin/ld: cannot find -lboost_system

### ISSUE THREAD

**Issue by zaie** [rohitgirdhar/AttentionalPoolingAction#14]
When make in folder "custom_ops", I got error:
==============================================
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_filesystem
/usr/bin/ld: cannot find -lboost_thread
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'pose_to_heatmap.so' failed
make: *** [pose_to_heatmap.so] Error 1
==============================================

I think maybe it's because "BOOST_DIR := /home/rgirdhar/Software/basic/boost/install2/" in Makefile file. How should I change the dir?

**Comment by rohitgirdhar** [comment]
You need to install [boost](http://www.boost.org/) libraries and set the path to where you install it. This path should have the `include/` and `lib/` folders with header files and compiled `.so` binaries.

**Comment by djmcg** [comment]
HI could You Advice How to insall boost libraries ??
I hava the same error with compile wallet to ARM.

**Comment by shashi97** [comment]
hahaha
