### ISSUE TITLE
HICO and HMDB51 dataset 

### ISSUE THREAD

**Issue by vra** [rohitgirdhar/AttentionalPoolingAction#16]
Hi @rohitgirdhar ,
Thanks for your great work! It's really helpful.  Can you give your pose data and feature data of HICO dataset and HMDB51 dataset? Thank you in advance. 👍

**Comment by rohitgirdhar** [comment]
Thanks for your interest! I have added the keypoints for HICO; will do for HMDB when I'm on a faster internet connection.

**Comment by rohitgirdhar** [comment]
Added HMDB as well

**Comment by vra** [comment]
Thanks! 👍
