### ISSUE TITLE
cannot generate tfrecord

### ISSUE THREAD

**Issue by hwjwayne** [rohitgirdhar/AttentionalPoolingAction#3]
dir of annotation and image files are set correctly, but when I run  "python gen_tfrecord_mpii.py", the following error occured:

Traceback (most recent call last):
  File "gen_tfrecord_mpii.py", line 259, in <module>
    main()
  File "gen_tfrecord_mpii.py", line 182, in main
    with open(_SPLITS_PATH.format(spl), 'r') as fin:
IOError: [Errno 2] No such file or directory: '../../src/data/mpii/lists/'

The link of rec file is also incorrect

**Comment by rohitgirdhar** [comment]
My bad, I forgot to push the dataset split files. Pushed them now.

**Comment by wemakefocus** [comment]
@rohitgirdhar Thanks for your code and answer, but I still cannot generate tfrecord yet. After I set the paths for MPII images and annotations file and run "python gen_tfrecord_mpii.py", another error occured:
Traceback (most recent call last):
  File "gen_tfrecord_mpii.py", line 259, in <module>
    main()
  File "gen_tfrecord_mpii.py", line 182, in main
    with open(_SPLITS_PATH.format(spl), 'r') as fin:
IOError: [Errno 21] Is a directory: '../../src/data/mpii/lists/'

**Comment by YinRui1991** [comment]
@wemakefocus   in gen_tfrecord_mpii.py you need to modify line 23 like this: _SPLITS_PATH = '/data/YinRui/AttentionalPoolingAction-master/src/data/mpii/lists/images_mpii_'   
add "images_mpii_" after "lists/"

**Comment by hawklucky** [comment]
I still cannot generate the tfreocrd because the function in "image_to_tfexample" need the parameter "salicon_image_data". And I don't know where it is?@rohitgirdhar @YinRui1991

**Comment by rohitgirdhar** [comment]
Actually that parameter was not required. I just removed it.
