### ISSUE TITLE
Error when running any one of the python files

### ISSUE THREAD

**Issue by BearVic** [rohitgirdhar/AttentionalPoolingAction#31]
The error displayed when I tried to evaluate the model:
tensorflow.python.framework.errors_impl.notfounderror: libopencv_ocl.so.2.4: cannot open shared object file: No such file or directory.

Does it mean I have to create the libopencv_ocl.so.2.4 file or need to modify some configuration file?

**Comment by rohitgirdhar** [comment]
Seems like tensorflow can not find an OpenCV library. Please refer to TF build instructions to compile correctly with opencv.
