### ISSUE TITLE
Failed to find any matching file for resnet_v1_101.ckpt

### ISSUE THREAD

**Issue by lxbaoding** [rohitgirdhar/AttentionalPoolingAction#32]
When I try to run the python3 train.py --cfg ../experiments/002_MPII_ResNet_withAttention.yaml,it cannot find the file resnet_v1_101.ckpt.Can you please provide it? Thanks!

**Comment by rohitgirdhar** [comment]
We use the standard TensorFlow pre-trained models, you can download from [there](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models).

**Comment by lxbaoding** [comment]
Thanks for your answer,but can the new training model be generated form the tandard TensorFlow pre-trained models? Isn't the file train.py for training a new model?

**Comment by rohitgirdhar** [comment]
We initialize from ImageNet pre-trained weights and then finetune the model.
