### ISSUE TITLE
Attentional pooling for CIFAR10/100, STL10 dataset

### ISSUE THREAD

**Issue by LiliMeng** [rohitgirdhar/AttentionalPoolingAction#6]
Thanks a lot for the paper and sharing the code.
It seems that for CIFAR10 dataset, the result is very similar with and without attentional pooling.

With: 92.87%
Without: 92.86%

ResNet 32 (residual blocks: 5-5-5, output_channels: 16-32-64 , number of parameters: 0.46 ) is used for this test. 

Is this attentional pooling dependent on special datasets?

**Comment by rohitgirdhar** [comment]
Thanks @LiliMeng for the feedback and trying out attentional pooling on CIFAR-10!
Here's what I think might be happening here (though feel free to correct me 🙂 ):
1. Given the connection (low-rank approx) we show to 2nd order pooling, a variant of which has been shown to be useful for fine-grained recognition ([bilinear cnn](http://vis-www.cs.umass.edu/bcnn/)), and concurrently for other fine-grained tasks like VQA ([relation nets](https://arxiv.org/abs/1706.01427)), the 10-way classification task on CIFAR might not be "fine-grained" enough.
2. Again using that connection to 2nd order pooling, I think attentional pooling would be most useful for tasks that require "interaction" features ($X^TX$); i.e. pair-wise features of one part of the image/video with another. This I think is especially true in action recognition and VQA, which might explain the recent success of similar self-attention methods for these tasks ([Attend and Interact](http://shallowdown.wixsite.com/chih-yao-ma/obj-interaction-video-understanding), [Non-local Neural Networks](https://arxiv.org/abs/1711.07971))

That said, our attention module is super light-weight, and seems to mostly maintain or improve performance; it might be useful to keep around in your network architectures 🙂

**Comment by LiliMeng** [comment]
Thanks a lot @rohitgirdhar  for your kind and detailed reply! :)

 I'll have a try to use large images and activity datasets.

**Comment by rohitgirdhar** [comment]
Thanks for trying the other experiments. Yes, the resolution of the image is quite important, as you want different features at the last layer focus on different areas of the image.
