### ISSUE TITLE
How to get top-down map or bottom-up map?

### ISSUE THREAD

**Issue by YinRui1991** [rohitgirdhar/AttentionalPoolingAction#8]
@rohitgirdhar Hi, can you give some advice about how to get top-down map or bottom-up map introduced in your paper? And is there a file in this repository I can use to get top-down map or bottom-up map ?
Thanks a lot!

**Comment by rohitgirdhar** [comment]
Actually I store two endpoints in the code (when generating the network) that essentially give the top-down and bottom up attention maps. [This](https://github.com/rohitgirdhar/AttentionalPoolingAction/blob/d45807b273baf8a560921ebfa81885b321f23de9/models/slim/nets/nets_factory.py#L309) is the top-down attention, and [this](https://github.com/rohitgirdhar/AttentionalPoolingAction/blob/d45807b273baf8a560921ebfa81885b321f23de9/models/slim/nets/nets_factory.py#L287) is the bottom-up.
