### ISSUE TITLE
Attentional pooling for UCF101

### ISSUE THREAD

**Issue by LiliMeng** [rohitgirdhar/AttentionalPoolingAction#9]
Thanks a lot for sharing the code.

Will attentional pooling do better on UCF101? 
It seems that the performance is almost the same without using pre-trained model. Both are around 40%. 

Any suggestions?

Thanks a lot!

**Comment by YinRui1991** [comment]
@LiliMeng Hi, you can try to add attentional pooling layer to LSTM if you want to improve accuracy on action dataset, such as UCF101. I think that only CNN is not enough for action classification and RNN is good at temporal work. Attentional pooling is a good observer that you can see and show where CNNs focus on.

**Comment by rohitgirdhar** [comment]
Thanks for trying the experiment on UCF101. This is a little surprising as I would expect things to improve on UCF101.. I guess one reason could be that most actions in UCF don't require focusing on image regions, as the scene context itself gives away the action..
